# Generated by Django 5.0.2 on 2024-09-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='TestScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='TestTotalScore',
            field=models.IntegerField(default=0),
        ),
    ]
