# Generated by Django 5.0.2 on 2024-10-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_api', '0004_alter_usernotes_notetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='notetitle',
            field=models.TextField(default='', verbose_name='Note Title'),
        ),
    ]
